### ISSUE TITLE
nft_transfer doesn't match standard

### ISSUE THREAD

**Issue by zcstarr** [Mintbase/mintbase-core#6]
Summary:  Nft transfer approval_id is in old standard format. The standard recently updated to u64 vs U64 implementations, this means that when a user calls nft_transfer on their smart contract or another contract tries to call nft_transfer it will fail due to the serialization change. 

Motivation: To have a safe nft_transfer that matches the rest of the standard implementations.

One of the problematic spaces:
https://github.com/Mintbase/mintbase-core/blob/fdf1eff84e81a5c1bc06f698c98d7182b1753315/mintbase-deps/src/impls.rs#L1512

**Comment by evergreen-trading-systems** [comment]
fixed https://github.com/Mintbase/mintbase-core/releases/tag/v0.1
