### ISSUE TITLE
Update store contract to use empty base URI moving forward

### ISSUE THREAD

**Issue by cif** [Mintbase/mintbase-core#62]
When minting on a single contract, it's possible that I may want to use reference material hosted in another location other than arweave in the future.

**Comment by tifrel** [comment]
This requires the minter to be aware of a present base URI. If present, use arweave hash for reference and media, if not present, use `https://arweave.net/{arweave_hash}` instead.

**Comment by cif** [comment]
This could be done without contact changes on store side (perhaps factory/mintbase js) simply on the contract creation side e.g. not specifying base URI.  Will revisit this later

**Comment by microchipgnu** [comment]
https://github.com/Mintbase/mintbase-js/pull/138 

Let's merge & close this?
