### ISSUE TITLE
Bug: nft_transfer_call uses excess gas?

### ISSUE THREAD

**Issue by zcstarr** [Mintbase/mintbase-core#7]
Summary: 
`nft_transfer_call` implementation uses twice the amount of gas as what's required. I noticed the gas for resolving the transfer is actually the same as the gas required for performing the transfer call itself. The resolution gas should in theory be the same as the NFT_TRANSFER_RESOLVE approximately Gas(10_000_000_000_000) + some gas maybe for whatever you're doing within the resolution.

Motivation: 
The gas costs for calling transfer_call on a mintbase NFT is super high. If you're looking at 3rd party integrations, the high gas cost can be prohibitive for making calls. Additionally makes the transactions more expensive than they need to be. 

Suggested fix: 
Reduce the gas amount required for resolving the tx to the minimum req. ~ Gas(10_000_000_000_000) . Additionally the NFT_TRANSFER_CALL_GAS calculation already adds addition NFT_TRANSFER_RESOLVE gas, so I would split this out as well into it's components. 
```rs

        ext_on_transfer::nft_on_transfer(
            pred,
            owner_id.clone(),
            token_id,
            msg,
            receiver_id.clone(),
            NO_DEPOSIT,
            Gas(GAS_NFT_TRANSFER_CALL),
        )
        .then(store_self::nft_resolve_transfer(
            owner_id,
            receiver_id,
            token_id.0.to_string(),
            None,
            env::current_account_id(),
            NO_DEPOSIT,
            Gas(GAS_NFT_TRANSFER_CALL),
        ))
/// right now GAS_NFT_TRANSFER_CALL contains the resolve gas as well.
```
into 
```rs
       const GAS_NFT_TRANSFER:Gas = Gas(25_000_000_000_000);
       const GAS_NFT_TRANSFER_RESOLVE:Gas = Gas(10_000_000_000_000);
        ext_on_transfer::nft_on_transfer(
            pred,
            owner_id.clone(),
            token_id,
            msg,
            receiver_id.clone(),
            NO_DEPOSIT,
            Gas(GAS_NFT_TRANSFER),
        )
        .then(store_self::nft_resolve_transfer(
            owner_id,
            receiver_id,
            token_id.0.to_string(),
            None,
            env::current_account_id(),
            NO_DEPOSIT,
            Gas(GAS_NFT_TRANSFER_RESOLVE),
        ))
```        

Lines in question:
https://github.com/Mintbase/mintbase-core/blob/b98ffd09b3555516e622db6ae00103530a39b5c8/mintbase-deps/src/impls.rs#L1579

**Comment by evergreen-trading-systems** [comment]
This is a limitation of NEAR. Currently NEAR doesn't provide any way to calculate how much gas is being utilised in flight as mentioned here https://github.com/near/near-sdk-rs/issues/637

Furthermore, the same contract call can use different amounts of gas depending on the arguments and caller - very unideal. 

The only alternative is to thoroughly test contract calls with a variety of arguments to find a medium GAS value - a time consuming process that cannot be afforded. I'd welcome a pull request that details such findings.

There is a issue on the core NEAR repo that goes into depth about this if you want to read more on it - https://github.com/near/nearcore/issues/6150

closing

**Comment by zcstarr** [comment]
Hey thanks for having a look, and the linkthrus.  Just following the standards estimations +paras's guesses at what gas should roughly be.  The real problem isn't the first method call/ that's going to be largely 3rd party contract stuff ( completely unknown), it's the second method. 
```
store_self::nft_resolve_transfer(
            owner_id,
            receiver_id,
            token_id.0.to_string(),
            None,
            env::current_account_id(),
            NO_DEPOSIT,
            Gas(GAS_NFT_TRANSFER_CALL),
        )
```        
 The gas for store_self::nft_resolve_transfer should be more easily estimated, in theory much less than the GAS_NFT_TRANSFER_CALL. 
 
 I can take stab at doing an estimation, and showing some numbers, will ack back with a PR when I get a chance. 
 
 thanks again!
